set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set number
set relativenumber

set cursorline
hi cursorline cterm=none term=none
autocmd WinEnter * setlocal cursorline
autocmd WinLeave * setlocal nocursorline
highlight CursorLine ctermbg=234
