set tabstop=8
set softtabstop=8
set shiftwidth=8
set expandtab
set number
set relativenumber

set cursorline
hi cursorline cterm=none term=none
autocmd WinEnter * setlocal cursorline
autocmd WinLeave * setlocal nocursorline
highlight CursorLine ctermbg=234
